project:
  type: website
  output-dir: docs
  pre-render:
    - mapsR.R
  
website:
  page-navigation: true
  title: "ParksCan_GEOBON"
  navbar:
    background: primary
    search: true
    left:
      - text: "Home"
        file: index.qmd
      - sidebar:Logistics
      - sidebar:General_framework
      - sidebar:biodiversity
      - sidebar:Carbon_storage
      - sidebar:traditional_food_security
      - sidebar:spatial_prioritization
      

  sidebar:
    - id: Logistics
      title: "Logistics"
      style: "docked"
      background: light
      collapse-level: 3
      contents:
        - Logistics.qmd
        
    - id: General_framework
      title: "General_framework"
      contents:
        - General_framework.qmd
        - GEOBON_Framework.qmd
        - ecosystem_services.qmd
        - essential_variables.qmd
        - indicators.qmd

        
    - id: biodiversity
      title: "Biodiversity"
      contents: 
        - biodiversity.qmd
        
    - id: Carbon_storage
      title: "Carbon storage"
      contents:
        - Carbon_storage.qmd
        - Quantifying_CS.qmd
        - Services_CS.qmd
        - Case_studies_CS.qmd
        - Monitoring_CS.qmd
        
    - id: traditional_food_security
      title: "Traditional food security"
      contents:
        - traditional_food_security.qmd
        - Freshwater_fisheries.qmd
        - Foraging_wild_foods.qmd
        
    - id: spatial_prioritization
      title: "Spatial prioritization"
      contents:
        - spatial_prioritization.qmd

   
format:
  html:
    theme: cosmo
    css: styles.css
    page-layout: article
    toc: false
    


editor: visual

 