project:
  type: website
  output-dir: docs
  pre-render:
    - glossary.R
    - mapsR.R
  
website:
  page-navigation: true
  title: "ParksCan_GEOBON"
  navbar:
    background: primary
    search: true
    left:
      - text: "Home"
        file: index.qmd
      - sidebar:Logistics
      - sidebar:frameworks
      - sidebar:study_area
      - sidebar:Carbon_storage
      - sidebar:Freshwater_fisheries

  sidebar:
    - id: Logistics
      title: "Logistics"
      style: "docked"
      background: light
      collapse-level: 3
      contents:
        - Logistics.qmd
    - id: frameworks
      title: "Frameworks"
      contents:
        - frameworks.qmd
        - ecosystem_services.qmd
        - biodiversity.qmd
        - dual_frameworks.qmd
        - GEOBON_Framework.qmd
        - essential_variables.qmd
        - indicators.qmd
    - id: study_area
      title: "Study area"
      contents: 
        - study_area.qmd
    - id: Carbon_storage
      title: "Carbon storage"
      contents:
        - Carbon_storage.qmd
        - Quantifying_CS.qmd
        - Services_CS.qmd
        - Case_studies_CS.qmd
        - Monitoring_CS.qmd
    - id: Freshwater_fisheries
      title: "Freshwater fisheries"
      contents:
        - Freshwater_fisheries.qmd

   
format:
  html:
    theme: cosmo
    css: styles.css
    page-layout: article
    toc: false
    


editor: visual

 