---
title: "Essential variables"
format:
  html:
    self-contained: true
    link-external-icon: true
    link-external-newwindow: true
toc: true
editor: visual
---

"All essential variables represent a minimum collection of data or measurements that capture a specific dimension of the phenomena of interest and are critical for detecting change acrossspace and time \[13,16\]. Essential variables are therefore located at the interface between data (primary observations), indicators (synthetic or derived metrics), and user-specific societal or policy goals (e.g. Sustainable Development Goals)." ([Balvanera et al 2022](https://www.sciencedirect.com/science/article/abs/pii/S1877343522000045)).

Two main groups of essential variables have been defined: **Essential Biodiversity Variables** (**EBVs**) and **Essential Ecosystem Services Variables** (**EESVs**).

**In progress.....**

::: panel-tabset
## Essential Biodiversity Variables **EBVs**

An **Essential Biodiversity Variable** (**EBV**) is a measurement required for study, reporting, and management of biodiversity change ([Pereira et al 2013](https://www.science.org/doi/abs/10.1126/science.1229931)).

EBVs are biological state variables and they are selected to capture biodiversity change within aspeciﬁed range of spatial and temporal grain and extent" ([Schmeller et al 2017](https://link.springer.com/article/10.1007/s10531-017-1386-9#:~:text=An%20EBV%20cube%20encapsulates%20a,across%20space%20and%20through%20time.)).

GEO BON working groups have defined [6 EBVs classes](https://geobon.org/ebvs/what-are-ebvs/) that captures all levels of biodiversity.

| EBV class                                                                         | Description                                                            |
|--------------------------------------|---------------------------------|
| [Genetic composition](https://onlinelibrary.wiley.com/doi/full/10.1111/brv.12852) | Genetic diversity (richness and heterozygosity)                        |
|                                                                                   | Genetic differentiation (number of genetic units and genetic distance) |
|                                                                                   | Effective population size                                              |
|                                                                                   | Inbreeding                                                             |
| [Species populations](https://www.nature.com/articles/s41559-019-0826-1)          | Species distributions                                                  |
|                                                                                   | Species abundances                                                     |
| [Species traits](https://www.nature.com/articles/s41559-018-0667-3)               | Morphology                                                             |
|                                                                                   | Physiology                                                             |
|                                                                                   | Phenology                                                              |
|                                                                                   | Movement                                                               |
|                                                                                   | Reproduction                                                           |
| Community composition                                                             | Community abundance                                                    |
|                                                                                   | Taxonomic/phylogenetic diversity                                       |
|                                                                                   | Trait diversity                                                        |
|                                                                                   | Interaction diversity                                                  |
| Ecosystem functioning                                                             | Primary productivity                                                   |
|                                                                                   | Ecosystem phenology                                                    |
|                                                                                   | Ecosystem disturbances                                                 |
| Ecosystem structure                                                               | Live cover fraction                                                    |
|                                                                                   | Ecosystem distribution                                                 |
|                                                                                   | Ecosystem Vertical Profile                                             |

## Essential Ecosystem Services Variables (EESVs)

"We define **Essential Ecosystem Services Variables (EESVs**) as the minimum set of core variables needed to identify key changes in the interactions between nature and society that contribute to human well-being through ecosystem services." ([Balvanera et al 2022](#0){style="font-size: 11pt;"}).

[Balvanera et al (2022](https://www.sciencedirect.com/science/article/abs/pii/S1877343522000045)) proposed that "EESV classes can be operationalized to document changes in different elements of ecosystem services across space, time, and societal contexts.

| **EESVs classes**          | Description                                                                                                                                                                         |
|---------------|---------------------------------------------------------|
| Ecological supply          | the ecosystem structure and functions that underlie the potential capacity of ecosystems to provide ecosystem services                                                              |
| Anthropogenic contribution | the efforts that humans invest to enhance ecological supply and to make use of ecosystem services                                                                                   |
| Demand                     | the explicitly or implicitly expressed human desire or need for an ecosystem service, in terms of its quantity or quality, irrespective of whether awareness exists about such need |
| Use                        | the active or passive appropriation of an ecosystem service by people                                                                                                               |
| Instrumental value         | the importance of an ecosystem service to societies or individuals as a means to achieve a specific end (e.g., some dimension of human well-being)                                  |
| Relational value           | the importance ascribed to how ecosystems contribute to desirable and meaningful interactions between humans and nature and between humans in relation to nature.                   |
:::
