---
title: "Frameworks"
format:
  html:
    self-contained: true
    link-external-icon: true
    link-external-newwindow: true
toc: true
editor: visual
---

We summarized a preliminary review of frameworks that have been proposed to (i) protect and manage biodiversity and ecosystem; (ii) inform decision makers and (iii) guide global, national and regional policies to address biodiversity loss, prevent the erosion of ecosystem services, support sustainable use of natural resources, and integrate local communities and indigenous knowledge systems.

Most of these frameworks overlap each other and also overlap with CBD goals, indicators and expected results. [GEO BON framework](https://geobon.org/), is an overarching framework aimed to measure, assess and monitor biodiversity and ecosystem services.

For instance, some global integrated assessment frameworks ([FAO-UN, 2020](https://www.fao.org/3/CA8200EN/CA8200EN.pdf)) offer guidance to nations and other stakeholders for implementing programs to monitor and report on peatland's state and management: [Sustainable Development Goals (SDGs)](https://sdgs.un.org/2030agenda), [The Sendai Framework for Disaster Risk Reduction (DRR)](https://www.preventionweb.net/files/43291_sendaiframeworkfordrren.pdf), and [The Ramsar Convention on Wetlands](https://www.ramsar.org/). Other frameworks offer room to incorporate and evaluate some aspects of these ecosystems, for example: [The United Nations Framework Convention on Climate Change](https://unfccc.int/resource/docs/convkp/conveng.pdf) and Fire Monitoring Initiatives (e.g.,[FireMARS Canada](https://natural-resources.canada.ca/our-natural-resources/forests/wildland-fires-insects-disturbances/fire-monitoring-reporting-tool/13159)). However, spatially explicit assessment and impact evaluation is not fully supported and integrated by these frameworks.

GEO BON is a framework to measure, monitor, assess and report all levels of biodiversity (genetic, populations, communities, species and ecosystems) and recently ecosystem services. It provides spatial explicit tools that can be applied at different spatial scales (from local to national and global). Integrating multiple knowledge system is also fundamental part of GEO BON development.

In the next sections, we start describing the GEO BON framework, followed by three sections: ecosystem services (, essential variables and indicators. Finally we present some multiple/dual frameworks attempting to prevent simultaneously overarching biodiversity threats, for instance biodiversity loss and climate change.
