---
title: "Freshwater fisheries"
format:
  html:
    self-contained: true
    link-external-icon: true
    link-external-newwindow: true
toc: true
editor: visual
---

**in progress....**

# Introduction

Globally, a key source of food providing high quality protein and supporting healthy diets is fish ([Béné et al., 2016](https://www.sciencedirect.com/science/article/abs/pii/S0305750X15002892?via%3Dihub)). Subsistence fisheries are meant to provide enough food for the fisher and their family/community. These small- scale fisheries are essential to food security for many communities but also support the culture and sense of place of many indigenous peoples ([McClanahan, Allison and Cinner, 2015](https://onlinelibrary.wiley.com/doi/10.1111/faf.12045)). Typically, subsistence fisheries are more sustainable than large-scale commercial fishing but can be heavily impacted by these practices as they rely on the same stocks of fish ([Béné et al., 2016](https://www.sciencedirect.com/science/article/abs/pii/S0305750X15002892?via%3Dihub)). As such, many communities around the world are facing reduced catch as a consequence of declining stocks, threatening their food security and culture ([Pauly, Watson and Alder, 2005](https://royalsocietypublishing.org/doi/10.1098/rstb.2004.1574)).

::: panel-tabset
## How to measure it

## Case studies

Here, we discuss several case studies where issues of food security arose, from which lessons can be learnt for the HJBL region. All case studies discussed here involve indigenous communities relying on fish as a source of food but from different regions of the world: Alaska, Manitoba, Ontario, Nunavut, the Northwest Territories, Greenland and New Zealand.

**New Zealand**

The Māori, the indigenous people of New Zealand, make up 15% of the country's population but 16% of them report being food insecure as opposed to 7% in the rest of the population ([University of Otago and Ministry of Health, 2011](https://www.health.govt.nz/system/files/documents/publications/a-focus-on-nutrition-v2.pdf)). This difference has mainly been attributed to lower income of Māori households ([Rashbrooke, 2013](https://img.scoop.co.nz/media/pdfs/1306/Inequality_book_summary.pdf)). Traditional food practices were replaced following colonization as access to traditional foods decreased and have been largely replaced by the international food system ([McKerchar et al., 2015](https://journals.sagepub.com/doi/abs/10.1177/1757975914543573)). Two solutions to these problems were identified during workshops done in collaboration with key stakeholders and from

published work led by Māori researchers:

\- Increase the availability of traditional foods in households by replenishing fish stocks and communal gardening projects.

\- Develop traditional food-based industries to generate income through employment opportunities.

One key element in increasing traditional food availabilities in New Zealand was the legal recognition of Māori rights to manage freshwater habitats, where tribes were able to challenge development legally, waters (and therefore food) were protected ([The Waitangi Tribunal, 1984](https://forms.justice.govt.nz/search/Documents/WT/wt_DOC_68496990/Kaituna%20River%201984.pdf)) but not where their property rights were not recognised ([Memon and Kirk, 2011](https://researcharchive.lincoln.ac.nz/handle/10182/3312)).

Additionally, local fishery areas of special importance to Māori people were given particular legal recognition, allowing tribes to engage more fully in management ([Memon, Sheeran and Ririnui, 2003](https://www.researchgate.net/publication/249001912_Strategies_for_Rebuilding_Closer_Links_between_Local_Indigenous_Communities_and_Their_Customary_Fisheries_in_AotearoaNew_Zealand)). However, establishing such areas remains challenging to do and the Minister of Fisheries maintains final decision-making power (Jackson, 2008). More effective at protecting fish species for traditional food are the legally protected reserves where commercial fishing is banned (Te Karaka, 2009).

In all, strengthening food security for Māori people has been helped through the settlement of historical grievances between the communities and the Crown that resulted in the return of legal rights and governance systems allowing them to play an active role in the management of resources. However, tensions between the government and Māori goals around resource management remain, especially around water rights and fisheries. Additionally, economic development such as dairy farming continues to pollute waterways and overfishing depletes fish stocks, threatening the traditional fisheries of the Māori.

**Alaska**

The majority of Alaskan Natives now lives in urban centres, yet many small communities (10-600 people) still live in isolated areas that are often only accessible by boat or plane ([Goldsmith, 2008](https://iseralaska.org/static/legacy_publication_links/researchsumm/UA_RS10.pdf)). In these regions, people rely almost exclusively on a subsistence lifestyle largely reliant on wild caught fish (Goldsmith, 2008). However, people today rely on motorised boats that are expensive to maintain and fuel, creating a demand for cash that results in many working seasonally (or leaving for good) in urban centres to be able to afford to eat ([Nuttall et al., 2004](https://www.amap.no/documents/download/1093/inline)). Additionally, environmental change has resulted in dramatic ecological transitions, such as lakes drying up, and consequently significant declines in freshwater fish species ([Schindler, 2001](https://cdnsciencepub.com/doi/10.1139/f00-179)). These environmental changes can be sudden and unexpected, forcing people to adapt. Even though Alaskan Natives have a legally protected right to fish following their long held customs and traditions ([Fall and Wolfe, 2012](https://www.adfg.alaska.gov/static/regulations/regprocess/gameboard/pdfs/2013-2014/Statewide_03-14-14/rcs/rc011_ADFG_Subsistence_Update.pdf)), state and federal law on wildlife management restricts people's ability to adapt by imposing fishing seasons, quotas and area closures that are not informed by the changing reality on the ground ([Loring and Gerlach, 2009](https://d1wqtxts1xzle7.cloudfront.net/30753152/loring_and_gerlach_2009_food_culture_and_human_health_final_reprint-libre.pdf?1391787519=&response-content-disposition=inline%3B+filename%3DFood_culture_and_human_health_in_Alaska.pdf&Expires=1688494276&Signature=FALYmyEZZAw2n9LwlIDhr34g0EO5t2B6Iipqyecp1JXmJtHZ-BoFuMqaUEoKuVTCz4XlBbz4~I2Qb9Fh0Kt1dNqXN~IDFncvKsRGhu2c5EXIhltxKXZ8Oh4fWY9OceOXNuhQdGjfSUUHRPQHPL5AXw85bb57Bes-Aaug4uphGCTNQN36G~RX-QSA5E~O7VMVT-7~Hhx6x7wGTBoKo0mXU03pOmC-lGAO9qtbEXJflf3py-h841uQzM4cm1dRRDyMyIrC81oTbUK~uALlkaNa6ojs8vgQgetdLt1VodDENkrttU2pE0Vh893QVVLRmyAPtH~Wd90tAm-HmPxjdo70Iw__&Key-Pair-Id=APKAJLOHF5GGSLRBV4ZA)). As a result, isolated communities are having to rely on long shelf-life foods from multinational corporations instead of traditional foods, affecting food security and health outcomes ([Loring and Gerlach, 2009](https://d1wqtxts1xzle7.cloudfront.net/30753152/loring_and_gerlach_2009_food_culture_and_human_health_final_reprint-libre.pdf?1391787519=&response-content-disposition=inline%3B+filename%3DFood_culture_and_human_health_in_Alaska.pdf&Expires=1688494276&Signature=FALYmyEZZAw2n9LwlIDhr34g0EO5t2B6Iipqyecp1JXmJtHZ-BoFuMqaUEoKuVTCz4XlBbz4~I2Qb9Fh0Kt1dNqXN~IDFncvKsRGhu2c5EXIhltxKXZ8Oh4fWY9OceOXNuhQdGjfSUUHRPQHPL5AXw85bb57Bes-Aaug4uphGCTNQN36G~RX-QSA5E~O7VMVT-7~Hhx6x7wGTBoKo0mXU03pOmC-lGAO9qtbEXJflf3py-h841uQzM4cm1dRRDyMyIrC81oTbUK~uALlkaNa6ojs8vgQgetdLt1VodDENkrttU2pE0Vh893QVVLRmyAPtH~Wd90tAm-HmPxjdo70Iw__&Key-Pair-Id=APKAJLOHF5GGSLRBV4ZA)).

To cope with food insecurity, local communities have formed a network of cooperation based on cultural traditions, relationships and a mix of subsistence and cash economies (Kofinas et al., 2016). Strong social bonds between communities and households of Alaskan Natives and a culture of sharing mean that households that typically obtain more resources than others (food and cash) share food with others on a needs basis. However, even households with relatively more resources are often still food insecure and have at least one member in employment. This situation highlights differences at the household level with some households being more vulnerable to economic and climatic changes and an inability to fully achieve food security by the different communities without relying on a cash input from outside (Kofinas et al., 2016).

+-------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------+----------------+
| Case study                                      | Description                                                                                                                                                                                       | Actions taken                                                                                                                                | Impact/results |
+=================================================+===================================================================================================================================================================================================+==============================================================================================================================================+================+
| The Māori, the indigenous people of New Zealand | Traditional food practices were replaced following colonization as access to traditional foods decreased and have been largely replaced by the international food system (McKerchar et al., 2015) | \- Increase the availability of traditional foods in households by replenishing fish stocks and communal gardening projects.                 |                |
|                                                 |                                                                                                                                                                                                   |                                                                                                                                              |                |
|                                                 |                                                                                                                                                                                                   | \- Legal recognition of Māori rights to manage freshwater habitats                                                                           |                |
|                                                 |                                                                                                                                                                                                   |                                                                                                                                              |                |
|                                                 |                                                                                                                                                                                                   | \- Develop traditional food-based industries to generate income through employment opportunities.                                            |                |
+-------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------+----------------+
|                                                 |                                                                                                                                                                                                   |                                                                                                                                              |                |
+-------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------+----------------+
|                                                 |                                                                                                                                                                                                   |                                                                                                                                              |                |
+-------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------+----------------+

## Monitoring

## Tools
:::
