---
title: "Genetic_composition"
format:
  html:
    self-contained: true
    link-external-icon: true
    link-external-newwindow: true
toc: true
editor: visual
---

::: panel-tabset
## **Aim**

Protect and safeguard genetic diversity (within and between species populations) of wild, managed, and cultivated species for human well-being and ecosystem resilience.

## **Metrics/ EBVs/EESVs**

### Proposed EBVs

[Hoban et al (2022)](https://onlinelibrary.wiley.com/doi/full/10.1111/brv.12852) have proposed the following Genetic Composition Essential Biodiversity Variables (EBVs),

-   **Genetic Diversity** (Richness and evenness)

-   **Genetic Differentiation** (Number of genetic units and differentiation between units)

-   **Inbreeding**

-   **Effective Population Size** (Ne)

### EBVs characteristics

[Hoban et al (2022)](https://onlinelibrary.wiley.com/doi/full/10.1111/brv.12852) summarized the four proposed Genetic Composition Essential Biodiversity Variables (EBVs) in Table 1, including their definitions, possible values, interpretation, and a ranking from low (+) to high (+++) on various EBV criteria (rows).

**Definition**

+------------------------------------------------+---------------------------------------------------------------------+---------------------------------------------------+--------------------------------------------------------------+----------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------+
| **Genetic..**                                  | **..diversity**                                                     | **Genetic**                                       | **differentiation**                                          | **Inbreeding**                                                                                     | **Effective populaton size (*Ne*)**                                                               |
+------------------------------------------------+---------------------------------------------------------------------+---------------------------------------------------+--------------------------------------------------------------+----------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------+
| **Richness**                                   | **Evenness**                                                        | **Number of genetic units**                       | **Differentiation between units**                            |                                                                                                    |                                                                                                   |
+------------------------------------------------+---------------------------------------------------------------------+---------------------------------------------------+--------------------------------------------------------------+----------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------+
| Count of the number of alleles in a population | Expected proportion of heterozygotes in a population at equilibrium | Number of genetic lineages/units within a species | Degree of genetic differentiation among populations or units | Degree of relatedness between pairs of individuals, mating among relatives, or identity by descent | Size of an ideal population that loses genetic variation at the same rate as the focal population |
+------------------------------------------------+---------------------------------------------------------------------+---------------------------------------------------+--------------------------------------------------------------+----------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------+

+---------------------------------------------------+------------------------------------------------+-------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------+
| **Genetic EBV**                                   | **Genetic**                                    | **diversity**                                                                 | **Genetic**                                                                                                    | **differentiation**                                                                                                                          | **Inbreeding**                                                                                     | **Effective populaton size (*Ne*)**                                                               |
+---------------------------------------------------+------------------------------------------------+-------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------+
|                                                   | **Richness**                                   | **Evenness**                                                                  | **Number of genetic units**                                                                                    | **Differentiation between units**                                                                                                            |                                                                                                    |                                                                                                   |
+---------------------------------------------------+------------------------------------------------+-------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------+
| Definition                                        | Count of the number of alleles in a population | Expected proportion of heterozygotes in a population at equilibrium           | Number of genetic lineages/units within a species                                                              | Degree of genetic differentiation among populations or units                                                                                 | Degree of relatedness between pairs of individuals, mating among relatives, or identity by descent | Size of an ideal population that loses genetic variation at the same rate as the focal population |
+---------------------------------------------------+------------------------------------------------+-------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------+
| Examples                                          | Allelic richness, nucleotide diversity (π)     | *H*~e~, *H~O~*                                                                | Number of distinct evolutionarily significant units or management units                                        | *F*~ST~, *G*~ST~, *D*~est~                                                                                                                   | *F*~IS~, *F*~ROH~, *F*~H~, *t*~m~--*t*~s~, *t*~m~                                                  | LD-based *N*~e~; *N*~e~ from temporal method                                                      |
+---------------------------------------------------+------------------------------------------------+-------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------+
| Range of values                                   | 0 to 1                                         | 0 to 1                                                                        | ≥1                                                                                                             | 0 to 1                                                                                                                                       | -1 to 1                                                                                            | Usually smaller than census population size                                                       |
+---------------------------------------------------+------------------------------------------------+-------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------+
| Level of organization                             | Population                                     | Individual/population                                                         | Across species range or specific region                                                                        | Across species range or specific region                                                                                                      | Individual (pairs or families)/population                                                          | Population                                                                                        |
+---------------------------------------------------+------------------------------------------------+-------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------+
| Interpretation of a change identified across loci | Decline indicates loss of adaptive capacity    | Decline indicates loss of adaptive capacity or increased levels of inbreeding | Loss of independent evolutionary or demographic units (probable loss of adaptations and long-term persistence) | Increased differentiation indicates more fragmentation (reduced gene flow) between units; decreased differentiation indicates homogenization | Increased inbreeding increases the chance of expression of deleterious alleles, reducing fitness   | Lower *N*~e~ increases genetic drift, inbreeding, and future loss of genetic variation            |
+---------------------------------------------------+------------------------------------------------+-------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------+
| Relevance to species status                       | +++                                            | ++                                                                            | +++                                                                                                            | ++                                                                                                                                           | +++                                                                                                | +++                                                                                               |
+---------------------------------------------------+------------------------------------------------+-------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------+
| Sensitivity to change over time                   | +++                                            | \+                                                                            | +++                                                                                                            | ++ (depends on life history and *N*~e~)                                                                                                      | +++ (depends on method)                                                                            | ++                                                                                                |
+---------------------------------------------------+------------------------------------------------+-------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------+
| Spatial scalability                               | +++                                            | \+                                                                            | +++                                                                                                            | ++                                                                                                                                           | \+                                                                                                 | \+                                                                                                |
+---------------------------------------------------+------------------------------------------------+-------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------+
| Feasibility                                       | +++                                            | +++                                                                           | +++                                                                                                            | +++                                                                                                                                          | ++ (depends on measure -- *F*~ROH~ currently less feasible)                                        | +/++ (depends on method -- single sample is more feasible                                         |
+---------------------------------------------------+------------------------------------------------+-------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------+
| Data available                                    | +++                                            | +++                                                                           | +++                                                                                                            | +++                                                                                                                                          | \+                                                                                                 | \+                                                                                                |
+---------------------------------------------------+------------------------------------------------+-------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------+

### How to calculate metrics?

## **Data sets**

+------------------------------------------------------------+-------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Field/other sources                                        | Lab/computer work                   | Data sets                                                                                                                                                                                      |
+============================================================+=====================================+================================================================================================================================================================================================+
| Biological sampling, biological collections, fossils, eDNA | DNA storage, extraction, sequencing | Raw data: [International Nucleotide Sequence Database Collaboration](https://www.insdc.org/)                                                                                                   |
|                                                            |                                     |                                                                                                                                                                                                |
|                                                            |                                     | Processed data: [GenBank](https://www.ncbi.nlm.nih.gov/genbank/), [BOLD](https://boldsystems.org/)                                                                                             |
|                                                            |                                     |                                                                                                                                                                                                |
|                                                            |                                     | Taxonomic and region specific: [CartograTree](https://treegenesdb.org/ct)                                                                                                                      |
+------------------------------------------------------------+-------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Census size of local populations                           |                                     | Global: [GBIF](https://www.gbif.org/), [North American Breeding Bird Survey](https://www.pwrc.usgs.gov/bbs/index.cfm?CFID=940148&CFTOKEN=5a58ca4280dca5d1-F1BBB960-CA44-1525-939C60A47BCBFF34) |
|                                                            |                                     |                                                                                                                                                                                                |
|                                                            |                                     | Canada:                                                                                                                                                                                        |
|                                                            |                                     |                                                                                                                                                                                                |
|                                                            |                                     | Region (Provinces):                                                                                                                                                                            |
|                                                            |                                     |                                                                                                                                                                                                |
|                                                            |                                     | Local:                                                                                                                                                                                         |
+------------------------------------------------------------+-------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                                                            |                                     |                                                                                                                                                                                                |
+------------------------------------------------------------+-------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

## **Indicators**

Several indicators have been proposed

-   Proportion of species populations with effective population sizes (Ne) \> 500. "The"Ne indicator" is currently included in the GBF monitoring framework as a headline indicator (A.5, CBD [2022e](https://www.cbd.int/doc/c/c9de/d8ef/7225d7bb822f39ad3426c52b/cop-15-02-en.pdf "CBD 2022e. Draft decisions for the fifteenth meeting of the Conference of the Parties to the Convention on Biological Diversity. CBD/COP/15/2. Page 18. UNEP. URL https://www.cbd.int/doc/c/c9de/d8ef/7225d7bb822f39ad3426c52b/cop-15-02-en.pdf"), previously A.0.4 CBD [2021c](https://www.cbd.int/doc/c/3303/d892/4fd11c27963bd3f826a961e1/wg2020-04-04-en.pdf "CBD 2021c. Proposed headline indicators of the monitoring framework for the post-2020 global biodiversity framework. CBD/WG2020/3/3/Add.1. UNEP. URL https://www.cbd.int/doc/c/d716/da69/5e81c8e0faca1db1dd145a59/wg2020-03-03-add1-en.pdf")) for Goal A." ([Hoban et al 2023](https://link.springer.com/article/10.1007/s10592-022-01492-0)), see also in [metadata for indicators](https://www.post-2020indicators.org/) A4.

[Hoban et al (2023)](https://link.springer.com/article/10.1007/s10592-022-01492-0){style="font-size: 11pt;"} also discussed additional indicators, for instance:

-   "Maintain genetic diversity within populations"

-   "No loss of distinct populations"

-   "The safeguarding" component indicator

-   "The genetic scored" indicator

+-------------------------------------------------------------------------------+---------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Indicator                                                                     | Type of indicator   | Rationale                                                                                                                                                                        | Targets (global, national regional)                                                                                                                                     |
+===============================================================================+=====================+==================================================================================================================================================================================+=========================================================================================================================================================================+
| Proportion of species populations with effective population sizes (Ne) \> 500 | Headline indicator  | ...is a metric for measuring the rate of loss of genetic diversity within populations. [metadata for indicators](https://www.post-2020indicators.org/){style="font-size: 11pt;"} | Global: Goal A - Target 4 ([CBD](https://www.cbd.int/article/cop15-cbd-press-release-final-19dec2022), [metadata for indicators](https://www.post-2020indicators.org/)) |
|                                                                               |                     |                                                                                                                                                                                  |                                                                                                                                                                         |
|                                                                               |                     |                                                                                                                                                                                  | Canada:                                                                                                                                                                 |
|                                                                               |                     |                                                                                                                                                                                  |                                                                                                                                                                         |
|                                                                               |                     |                                                                                                                                                                                  | Provinces:                                                                                                                                                              |
+-------------------------------------------------------------------------------+---------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| "Maintain genetic diversity within populations"                               |                     |                                                                                                                                                                                  |                                                                                                                                                                         |
+-------------------------------------------------------------------------------+---------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| "No loss of distinct populations"                                             |                     |                                                                                                                                                                                  |                                                                                                                                                                         |
+-------------------------------------------------------------------------------+---------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| "The safeguarding" component indicator                                        | Component indicator |                                                                                                                                                                                  |                                                                                                                                                                         |
+-------------------------------------------------------------------------------+---------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| "The genetic scored" indicator                                                |                     |                                                                                                                                                                                  |                                                                                                                                                                         |
+-------------------------------------------------------------------------------+---------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

### **How to calculate indicators?**

See indicator metadata form for ["The proportion of populations within species with a genetically effective population size \> 500."](https://www.post-2020indicators.org/pdfs/447?type=headline)
:::
