---
title: "Integrating multiple knowledge systems in the application of relevant tools and models for the conservation of biodiversity and carbon-rich ecosystems in the Hudson-James Bay Lowlands"
format:
  html:
    self-contained: true
    link-external-icon: true
    link-external-newwindow: true
toc: true
date-modified: last-modified
editor: visual
---

# Presentation

We organized this document to provide a preliminary context of this initiative and facilitate the communication among all partners. It will be updated regularly as we get more information and feedback. It will be also the basis of a white paper.

# Introduction

This initiative aims to **improve knowledge and application of tools, approaches, and models** that are appropriate at a Canadian scale for looking at how to address the dual **conservation of biodiversity and ecosystem carbon storage** to support the establishment and active management and restoration of protected and conserved areas.

Tools and approaches have been developed and applied in many countries and have been analyzed through several large processes (e.g., [Methodological Assessment Report on Scenarios and Models of Biodiversity and Ecosystem Services (IPBES 2016)](https://www.ipbes.net/document-library-catalogue/methodological-assessment-report-scenarios-and-models-biodiversity-and)), yet their application has been limited in Canada. As Parks Canada develops new approaches for establishing new protected and conserved areas and enhances active management and restoration efforts to better address the dual crises of biodiversity conservation and climate change, there is a need to explore how to refine and apply these tools and models to ecosystems across Canada. 

# Background

In 2021, Parks Canada Agency received funding for the Hudson--James Bay Lowlands Biodiversity Conservation and Sequestration Initiative. The goal of the Initiative is to work with a range of partners on studies regarding biodiversity conservation and the extent and quantity of carbon stocks and fluxes in wetland, peatland and coastal ecosystems in the Hudson--James Bay Lowlands (HJBL). This will advance understanding of:

a\) ecological integrity of the Hudson-James Bay Lowlands;

b\) ecosystem carbon stocks dynamics (storage and sequestration);

c\) a full suite of other ecosystem services; and

d\) active management approaches to achieve biodiversity and carbon conservation co-benefits. In turn, these results will be used to develop approaches and practices to establish and effectively manage protected areas and Other Effective Conservation Measures (OECMs) on a landscape scale across Canada.

To situate and guide the work to be carried out in the HJBL with Indigenous and other partners, there is a need to compile and validate spatially-explicit and scale-appropriate tools and models appropriate for Canadian ecosystems.

There is also a need to consider how Traditional Knowledge can weave appropriately into these tools and models. One element of addressing this need, is to conduct a stocktaking and analysis of existing tools, approaches, and models that already exist, prior to developing or applying new ones.

# Expected results

-   Improved knowledge of appropriate **spatially-explicit, and scale-appropriate tools and models** for biodiversity and carbon storage for the HJBL and other landscapes across Canada, including how these can support environmental reporting obligations. 

-   Improved understanding of frameworks and/or approaches that **achieve biodiversity and carbon conservation co-benefits** under different world views. 

-   Improved understanding of how to **weave Traditional Knowledge systems** into the application of identified tools and models.

# Activities

### Phase 1

-   Compile and review relevant tools, approaches, and models developed in other countries and/or by other organizations.

### Phase 2

-   Compile example case studies of application of relevant tools and approaches.

-   Convene a workshop of federal, provincial/territorial, Indigenous, non-governmental, academic and international experts to explore appropriate tools and models for landscape across Canada. 

-   Develop and deliver a discussion paper based on stocktaking exercise, case study analysis, and the outcome of the workshop with recommendations on appropriate tools and models, including the weaving of Traditional Knowledge into these that could be applied in the Hudson Bay-James Bay Lowlands and other landscapes across Canada.

###  Scope and expectations

**Parks Canada** is interested in compiling frameworks, methods, tools and case studies taking into account these criteria:

-   **Ecosystem services**: there are some preliminary priorities to explore within the wide range of ecological services :
    -   **Carbon storage**: HJBL harbor one of the most important peatland ecosystem in the world
    -   **Food security**: there are some traditional food priorities for indigenous and local communities to explore: freshwater fisheries, berries and geese.
-   **Biodiversity**: explore different levels of biodiversity (from species to ecosystems)
-   **Spatially-explicit, and scale-appropriate** models and tools
-   **Integrate multiple knowledge systems**
-   **Expectations**
    -   support active management
    -   protect species and landscapes
    -   develop good practices for biodiversity conservation and ecosystem services management
    -   Inform decision and policy makers
    -   Identify actions that can be implemented now (tactical) and others in the future

**GEO BON** is interested in developing a **regional BON**, that is an opportunity to implement its approach in a case study for Canada. A regional BON is a network of scientists (international/national/regional), government agencies, Indigenous organizations and conservation groups working together to harmonize and integrate efforts to **measure, assess and monitor biodiversity and ecosystem services** in the HJBL.

\
