---
title: "Quantifying carbon storage"
format:
  html:
    self-contained: true
    link-external-icon: true
    link-external-newwindow: true
toc: true
editor: visual
---

# Introduction

We discuss three general approaches for quantifying carbon storage for ecosystem services assessments and show how these three approaches could be adapted to account for peatland carbon dynamics in the Hudson Bay Lowlands. A comparison of the strengths, limitations, and best practices of each approach can be found in Table 1 which was reprinted from Schwantes et al. (in review). All three approaches rely on local site-specific field surveys for calibration and validation.

::: panel-tabset
## Stratify and Multiply

The first approach, **Stratify and Multiply**, relies on first stratifying or partitioning the study area into multiple unique land cover or ecosystem types ([Goetz et al. 2009](https://cbmjournal.biomedcentral.com/articles/10.1186/1750-0680-4-2), [Sharp et al. 2020](https://storage.googleapis.com/releases.naturalcapitalproject.org/invest-userguide/latest/en/index.html), [Martínez-López et al. 2019](https://www.sciencedirect.com/science/article/pii/S0048969718338737)). A reference or average carbon stock value is assigned to each cover type. The area of each cover type is then multiplied by the cover type's associated reference carbon stock value.

Many ecosystem service modeling platforms use a Stratify & Multiply approach, including the ARtificial Intelligence for Ecosystem Services, ARIES ([Martínez-López et al. 2019](https://www.sciencedirect.com/science/article/pii/S0048969718338737)) and the Integrated Valuation of Ecosystem Services and Tradeoffs, InVEST ([Sharp et al. 2020](https://storage.googleapis.com/releases.naturalcapitalproject.org/invest-userguide/latest/en/index.html)). Best practices include using local site-specific field surveys to derive reference carbon stock values and detailed site-specific land cover maps that account for environmental gradients that might influence carbon stock changes (*e.g.*, climate, soil characteristics, species composition, management, degradation, elevation, site history, wetland type, ecozone, etc.).

Carbon emissions can be assessed in a similar way. For example, maps of peatland types can be combined with estimates of Net Ecosystem Exchange and Methane emission rates compiled for each peatland type and region ([Webster et al. 2018](https://link.springer.com/article/10.1186/s13021-018-0105-5)).

## Direct Remote Sensing

The second approach, **Direct Remote Sensing**, uses a statistical or machine learning model to relate soil carbon field measurements to remotely sensed observations and other geospatial layers ([Goetz et al. 2009](https://cbmjournal.biomedcentral.com/articles/10.1186/1750-0680-4-2), [Sothe et al. 2021](https://agupubs.onlinelibrary.wiley.com/doi/full/10.1029/2021GB007213)). The Direct Remote Sensing approach captures spatial variability of carbon within land cover classes, which is often missed with the Stratify and Multiply approach. Best practices include using local site-specific field surveys for model calibration and validation as well as local site-specific geospatial layers for covariates (*e.g.*, topography, slope, soil type, wetland type, ecosystem type, soil characteristics, ecozone, etc.).

Carbon stock maps can be differenced to track changes over time. Another new approach relies on multi-temporal Light Detection and Ranging (LiDAR) to estimate changes in peatland elevation after a wildfire ([Reddy et al. 2015](https://www.sciencedirect.com/science/article/pii/S0034425715301401)). Peatlands are becoming more susceptible to wildfires due to lowering water tables under climate change and development ([Turetsky et al. 2015](https://www.nature.com/articles/ngeo2325)).

## Mass balance models

The third approach, **Mass balance models**, account for all key carbon pools and flows of carbon between these pools over time ([GFOI, 2016](https://www.fs.usda.gov/research/treesearch/56461), [Bona et al. 2020](https://www.sciencedirect.com/science/article/pii/S0304380020302350)). Mass balance models can track changes in carbon due to natural processes such as growth and decay as well as drivers of change including land use, wildfires, water table depth, and permafrost thaw.

Mass balance models are especially useful for understanding peatland carbon dynamics because they can account for the balance between the uptake of carbon and the emission of methane ([Bona et al. 2020](https://www.sciencedirect.com/science/article/pii/S0304380020302350)). Furthermore, these models can track changes in carbon due to increases in peatland disturbances, including droughts, permafrost thaw, and fires under climate change ([Bona et al. 2020](https://www.sciencedirect.com/science/article/pii/S0304380020302350), [Harris et al. 2022](https://esajournals.onlinelibrary.wiley.com/doi/10.1002/fee.2437)). When peatland permafrost thaws, previously frozen carbon can be decomposed, thereby releasing carbon dioxide and methane ([Hugelius et al. 2020](https://www.pnas.org/doi/full/10.1073/pnas.1916387117)).

Many modeling approaches have been implemented to estimate peatland carbon stocks in Canada including (1) the Canadian model for peatlands (CaMP) which accounts for wildfire disturbances but currently not permafrost thaw ([Bona et al. 2020](https://www.sciencedirect.com/science/article/pii/S0304380020302350), although permafrost thaw is currently being implemented), (2) dynamic global ecosystem models that incorporate permafrost dynamics ([Chaudhary et al. 2017](https://bg.copernicus.org/articles/14/4023/2017/bg-14-4023-2017.pdf)), and (3) inventory-based models ([Hugelius et al. 2020](https://www.pnas.org/doi/full/10.1073/pnas.1916387117)) that can also account for abrupt permafrost thaw ([Turetsky et al. 2020](https://www.nature.com/articles/s41561-019-0526-0)). Best practices include integrating local site-specific field data for calibration and validation as well as remotely sensed data for accurate spatially explicit disturbance detection (*e.g.*, [Zhou et al. 2021](https://iopscience.iop.org/article/10.1088/1748-9326/abf06d/meta), [Bona et al. 2020](https://www.sciencedirect.com/science/article/pii/S0304380020302350), Shaw et al. 2021).
:::

## Comparison of approaches to quantify carbon for ecosystem service assessments through time

Table 1. Comparison of approaches to monitor carbon storage and sequestration. Reprinted from Schwantes AM, Firkowski CR, Rodriguez PS,Gonzalez A and Fortin M-J. A comparison of approaches to quantify carbon for ecosystem service assessments through time. (In review at FACETS).

+---+---------------------------------------------------------------------------------------------------------------------------------------+---+-------------------------------------------------------------------------------------------------------------------------------------------------------------------+---+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---+------------------------------------------------------------------------------------------------------------------------------------------------------------------+---+
|   | **Approach**                                                                                                                          |   | **Strengths**                                                                                                                                                     |   | **Limitations**                                                                                                                                                                                       |   | **Best practices**                                                                                                                                               |   |
+---+---------------------------------------------------------------------------------------------------------------------------------------+---+-------------------------------------------------------------------------------------------------------------------------------------------------------------------+---+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---+------------------------------------------------------------------------------------------------------------------------------------------------------------------+---+
|   | **I.** **Stratify & Multiply Approach** multiply land use and land cover (LULC) maps with reference carbon stocks by LULC type        |   | ·       Easy to acquire the necessary data                                                                                                                        |   | ·       Typically, doesn't account for variability within land cover classes (*e.g.*, due to successional changes over time, climate, soil type, degradation, species composition, management)        |   | ·       Use detailed land cover class maps that account for species-specific forest types, forest stand-age, permanent crop type, climate, soils, and management |   |
|   |                                                                                                                                       |   |                                                                                                                                                                   |   |                                                                                                                                                                                                       |   |                                                                                                                                                                  |   |
|   |                                                                                                                                       |   | ·       Low financial costs for implementation                                                                                                                    |   | ·       Difficult to account for global change drivers other than land cover change, the effect of time lags, site history, and novel or mixed ecosystem types                                        |   | ·       Use locally derived reference carbon stocks and stock change factors instead of default values from IPCC wherever possible                               |   |
+---+---------------------------------------------------------------------------------------------------------------------------------------+---+-------------------------------------------------------------------------------------------------------------------------------------------------------------------+---+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---+------------------------------------------------------------------------------------------------------------------------------------------------------------------+---+
|   |                                                                                                                                       |   |                                                                                                                                                                   |   |                                                                                                                                                                                                       |   |                                                                                                                                                                  |   |
+---+---------------------------------------------------------------------------------------------------------------------------------------+---+-------------------------------------------------------------------------------------------------------------------------------------------------------------------+---+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---+------------------------------------------------------------------------------------------------------------------------------------------------------------------+---+
|   | **II. Direct Remote Sensing Approach** link remote sensing data with field measurements using statistical and machine learning models |   | ·       Account for spatial heterogeneity of carbon within land cover classes.                                                                                    |   | ·       Maps are not easily updated each year and hence are often only available for snapshots in time                                                                                                |   | ·       Validate and calibrate with local site-specific field surveys                                                                                            |   |
|   |                                                                                                                                       |   |                                                                                                                                                                   |   |                                                                                                                                                                                                       |   |                                                                                                                                                                  |   |
|   |                                                                                                                                       |   | ·       Account for spatial heterogeneity in areas where the land use or cover is uncertain (e.g., mixed ecosystems, ecosystems in transition, novel ecosystems). |   |                                                                                                                                                                                                       |   | ·       Develop automated algorithms that are easily updated each year                                                                                           |   |
+---+---------------------------------------------------------------------------------------------------------------------------------------+---+-------------------------------------------------------------------------------------------------------------------------------------------------------------------+---+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---+------------------------------------------------------------------------------------------------------------------------------------------------------------------+---+
|   |                                                                                                                                       |   |                                                                                                                                                                   |   |                                                                                                                                                                                                       |   |                                                                                                                                                                  |   |
+---+---------------------------------------------------------------------------------------------------------------------------------------+---+-------------------------------------------------------------------------------------------------------------------------------------------------------------------+---+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---+------------------------------------------------------------------------------------------------------------------------------------------------------------------+---+
|   | **III. Mass Balance Approach** model key carbon pools and flows between them                                                          |   | ·       Assess carbon stock changes across multiple pools through time                                                                                            |   | ·       Models will be most accurate if locally calibrated (e.g., use local site-specific field surveys for input data to improve model accuracy)                                                     |   | ·       Integrate field measurements for model calibration and validation                                                                                        |   |
|   |                                                                                                                                       |   |                                                                                                                                                                   |   |                                                                                                                                                                                                       |   |                                                                                                                                                                  |   |
|   |                                                                                                                                       |   | ·       Account for many drivers of change including urbanization, harvest, wildfires, and droughts                                                               |   | ·       Often computationally intensive                                                                                                                                                               |   | ·       Integrate remote sensing data for accurate disturbance detection (*e.g.*, harvest, wildfires, LULC change)                                               |   |
|   |                                                                                                                                       |   |                                                                                                                                                                   |   |                                                                                                                                                                                                       |   |                                                                                                                                                                  |   |
|   |                                                                                                                                       |   |                                                                                                                                                                   |   | ·       Require user expertise                                                                                                                                                                        |   |                                                                                                                                                                  |   |
|   |                                                                                                                                       |   |                                                                                                                                                                   |   |                                                                                                                                                                                                       |   |                                                                                                                                                                  |   |
|   |                                                                                                                                       |   |                                                                                                                                                                   |   | ·       Outputs are not always spatially explicit, but rather spatially referenced to coarser scale reporting areas, which can limit uses that require fine-scale spatially explicit carbon estimates |   |                                                                                                                                                                  |   |
+---+---------------------------------------------------------------------------------------------------------------------------------------+---+-------------------------------------------------------------------------------------------------------------------------------------------------------------------+---+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---+------------------------------------------------------------------------------------------------------------------------------------------------------------------+---+
|   |                                                                                                                                       |   |                                                                                                                                                                   |   |                                                                                                                                                                                                       |   |                                                                                                                                                                  |   |
+---+---------------------------------------------------------------------------------------------------------------------------------------+---+-------------------------------------------------------------------------------------------------------------------------------------------------------------------+---+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---+------------------------------------------------------------------------------------------------------------------------------------------------------------------+---+
